== Asciidoc Table

Lorem Ipsum pasajlarının birçok çeşitlemesi vardır. Ancak bunların büyük bir çoğunluğu mizah katılarak veya rastgele sözcükler eklenerek değiştirilmişlerdir. Eğer bir Lorem Ipsum (((pasaj)))pasajı kullanacaksanız, metin aralarına utandırıcı sözcükler gizlenmediğinden emin olmanız gerekir. İnternet'teki tüm Lorem Ipsum üreteçleri önceden belirlenmiş metin bloklarını yineler.


.Table Title (Optional)
[width="100%",options="header"]
|====================
|abcdefq |abcdefq |abcdefq |abcdefq
|abcdefq |abcdefq |abcdefq |abcdefq 
|abcdefq |abcdefq |abcdefq |abcdefq 
|====================

.Table Title (Optional)
|===
| Critère | MarkDown | Asciidoc |
|===

== Using Mathematical Formulas

http://www.mathjax.org/[MathJax] is an open source JavaScript display engine for (((mathematics)))mathematics that works in all browsers. In addition to png output, you can produce svg output also. Just change the extension.

.Tex Example
[math,file="tex-formula.png"]
--
\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{u} & = \rho x - y - xz \\
\dot{z} & = -\beta z + xyz
\end{align}
--

You can use (((Tex)))Tex or (((MathML)))MathML languages for describing mathematical formulas in AsciidocFX. AsciidocFX converts this textual formulas as png image.

.MathML Example
[math,file="mathml-formula.png"]
--
<math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
  <mi>x</mi>
  <mo>=</mo>
  <mrow>
    <mfrac>
      <mrow>
        <mo>&#x2212;</mo>
        <mi>b</mi>
        <mo>&#xB1;</mo>
        <msqrt>
          <msup>
            <mi>b</mi>
            <mn>2</mn>
          </msup>
          <mo>&#x2212;</mo>
          <mn>4</mn>
          <mi>a</mi>
          <mi>c</mi>
        </msqrt>
      </mrow>
      <mrow>
        <mn>2</mn>
        <mi>a</mi>
      </mrow>
    </mfrac>
  </mrow>
  <mtext>.</mtext>
</math>
--
